# -*- coding: utf-8 -*-
"""Task-1Iris Flower  Classification ML project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15mJHf4MaTqfmCSGtN1fMXYWf-gV47JYP

# **Loading Iris Dataset**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris

"""**Check Data**

"""

iris  = load_iris()

iris

from google.colab import drive
drive.mount('/content/drive')

"""**Checking Data**"""

iris.data

"""**Checking Target Value**"""

iris.target

"""**Checking Labels**"""

iris.target_names

"""**Checking Feature Names**"""

iris.feature_names

"""**Dependant and Independant Variables**"""

x = iris.data
y = iris.target

"""**Split data into train and Test part**"""

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.30, random_state =4)
x_train

"""**Use KNN Classifier**"""

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors =  3)

"""**Train KNN classifier**"""

knn.fit(x_train, y_train)

"""**Evaluate model**"""

y_pred = knn.predict(x_test)
y_pred

y_test

"""**Cheking Accuracy**"""

from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)
